//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guardian.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Guardian.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Guardian.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add item.
        /// </summary>
        public static string Home_AddItem {
            get {
                return ResourceManager.GetString("Home_AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        public static string Home_MyAccount {
            get {
                return ResourceManager.GetString("Home_MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My friends.
        /// </summary>
        public static string Home_MyFriends {
            get {
                return ResourceManager.GetString("Home_MyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owned.
        /// </summary>
        public static string Home_MyItems {
            get {
                return ResourceManager.GetString("Home_MyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan a NFC tag or choose one of below..
        /// </summary>
        public static string Home_NFCScanInfo {
            get {
                return ResourceManager.GetString("Home_NFCScanInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QueryCode.
        /// </summary>
        public static string Home_ScanQR {
            get {
                return ResourceManager.GetString("Home_ScanQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeView {
            get {
                return ResourceManager.GetString("HomeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ask to return.
        /// </summary>
        public static string ItemDetails_AskToReturn {
            get {
                return ResourceManager.GetString("ItemDetails_AskToReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category.
        /// </summary>
        public static string ItemDetails_Category {
            get {
                return ResourceManager.GetString("ItemDetails_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete item.
        /// </summary>
        public static string ItemDetails_Delete {
            get {
                return ResourceManager.GetString("ItemDetails_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get back!.
        /// </summary>
        public static string ItemDetails_GetBack {
            get {
                return ResourceManager.GetString("ItemDetails_GetBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to history.
        /// </summary>
        public static string ItemDetails_History {
            get {
                return ResourceManager.GetString("ItemDetails_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localization.
        /// </summary>
        public static string ItemDetails_Localization {
            get {
                return ResourceManager.GetString("ItemDetails_Localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string ItemDetails_Name {
            get {
                return ResourceManager.GetString("ItemDetails_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to owner.
        /// </summary>
        public static string ItemDetails_Owner {
            get {
                return ResourceManager.GetString("ItemDetails_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rent item!.
        /// </summary>
        public static string ItemDetails_RentTag {
            get {
                return ResourceManager.GetString("ItemDetails_RentTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status.
        /// </summary>
        public static string ItemDetails_Status {
            get {
                return ResourceManager.GetString("ItemDetails_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item rented!.
        /// </summary>
        public static string ItemDetails_TagRented {
            get {
                return ResourceManager.GetString("ItemDetails_TagRented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update tag.
        /// </summary>
        public static string ItemDetails_UpdateTag {
            get {
                return ResourceManager.GetString("ItemDetails_UpdateTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write to holder.
        /// </summary>
        public static string ItemDetails_WriteToHolder {
            get {
                return ResourceManager.GetString("ItemDetails_WriteToHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write to owner.
        /// </summary>
        public static string ItemDetails_WriteToOwner {
            get {
                return ResourceManager.GetString("ItemDetails_WriteToOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item details.
        /// </summary>
        public static string ItemDetailsView {
            get {
                return ResourceManager.GetString("ItemDetailsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get item!.
        /// </summary>
        public static string ItemDetected_Get {
            get {
                return ResourceManager.GetString("ItemDetected_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following item has been detected:.
        /// </summary>
        public static string ItemDetected_Info {
            get {
                return ResourceManager.GetString("ItemDetected_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item detected.
        /// </summary>
        public static string ItemDetectedView {
            get {
                return ResourceManager.GetString("ItemDetectedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string ItemsList_AllItems {
            get {
                return ResourceManager.GetString("ItemsList_AllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items:.
        /// </summary>
        public static string ItemsList_Items {
            get {
                return ResourceManager.GetString("ItemsList_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owned.
        /// </summary>
        public static string ItemsList_MyItems {
            get {
                return ResourceManager.GetString("ItemsList_MyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no items yet.
        /// </summary>
        public static string ItemsList_NoItems {
            get {
                return ResourceManager.GetString("ItemsList_NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rented.
        /// </summary>
        public static string ItemsList_RentedItems {
            get {
                return ResourceManager.GetString("ItemsList_RentedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items list.
        /// </summary>
        public static string ItemsListView {
            get {
                return ResourceManager.GetString("ItemsListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged as:.
        /// </summary>
        public static string LoggedAs {
            get {
                return ResourceManager.GetString("LoggedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginView {
            get {
                return ResourceManager.GetString("LoginView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item saved!.
        /// </summary>
        public static string NewItem_Confirmation {
            get {
                return ResourceManager.GetString("NewItem_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generate QR code.
        /// </summary>
        public static string NewItem_GenerateQR {
            get {
                return ResourceManager.GetString("NewItem_GenerateQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code sent to email: .
        /// </summary>
        public static string NewItem_QRSent {
            get {
                return ResourceManager.GetString("NewItem_QRSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save item!.
        /// </summary>
        public static string NewItem_SaveItem {
            get {
                return ResourceManager.GetString("NewItem_SaveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to RFID tag.
        /// </summary>
        public static string NewItem_SaveTag {
            get {
                return ResourceManager.GetString("NewItem_SaveTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item.
        /// </summary>
        public static string NewItemView {
            get {
                return ResourceManager.GetString("NewItemView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your email.
        /// </summary>
        public static string NewUser_Email {
            get {
                return ResourceManager.GetString("NewUser_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and go!.
        /// </summary>
        public static string NewUser_SaveAndGo {
            get {
                return ResourceManager.GetString("NewUser_SaveAndGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your username.
        /// </summary>
        public static string NewUser_Username {
            get {
                return ResourceManager.GetString("NewUser_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user.
        /// </summary>
        public static string NewUserView {
            get {
                return ResourceManager.GetString("NewUserView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag detected!.
        /// </summary>
        public static string NFC_TagDetected {
            get {
                return ResourceManager.GetString("NFC_TagDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag written!.
        /// </summary>
        public static string NFC_TagWritten {
            get {
                return ResourceManager.GetString("NFC_TagWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong tag format!.
        /// </summary>
        public static string NFC_WrongFormat {
            get {
                return ResourceManager.GetString("NFC_WrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection!.
        /// </summary>
        public static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag detected!.
        /// </summary>
        public static string QR_Detected {
            get {
                return ResourceManager.GetString("QR_Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code not valid!.
        /// </summary>
        public static string QR_Invalid {
            get {
                return ResourceManager.GetString("QR_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR-Code.
        /// </summary>
        public static string ScanQR {
            get {
                return ResourceManager.GetString("ScanQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new email.
        /// </summary>
        public static string Settings_NewEmail {
            get {
                return ResourceManager.GetString("Settings_NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new username.
        /// </summary>
        public static string Settings_NewUsername {
            get {
                return ResourceManager.GetString("Settings_NewUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User summary.
        /// </summary>
        public static string UserSummaryView {
            get {
                return ResourceManager.GetString("UserSummaryView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose category!.
        /// </summary>
        public static string Validation_ChooseCategory {
            get {
                return ResourceManager.GetString("Validation_ChooseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose status!.
        /// </summary>
        public static string Validation_ChooseStatus {
            get {
                return ResourceManager.GetString("Validation_ChooseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email field is required!.
        /// </summary>
        public static string Validation_EmailRequired {
            get {
                return ResourceManager.GetString("Validation_EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong email format!.
        /// </summary>
        public static string Validation_EmailWrong {
            get {
                return ResourceManager.GetString("Validation_EmailWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization field is required!.
        /// </summary>
        public static string Validation_LocalizationRequired {
            get {
                return ResourceManager.GetString("Validation_LocalizationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name field is required!.
        /// </summary>
        public static string Validation_NameRequired {
            get {
                return ResourceManager.GetString("Validation_NameRequired", resourceCulture);
            }
        }
    }
}
